### ISSUE TITLE
Disable buf_redux feature of sqlite3-parser

### ISSUE THREAD

**Issue by gwenn** [libsql/sqld#125]
As you already have the whole SQL query in memory here:
https://github.com/libsql/sqld/blob/4f0368b3db0647d682ad1f15414378166bcc035e/sqld/src/query_analysis.rs#L104
you should be able to remove the `buf_redux` feature here:
https://github.com/libsql/sqld/blob/4f0368b3db0647d682ad1f15414378166bcc035e/sqld/Cargo.toml#L40
```toml
sqlite3-parser = { git = "https://github.com/gwenn/lemon-rs.git", rev = "be6d0a96c4424fada2e068b51c25d1fdc9f983f4", default-features = false, features = [
    "YYNOERRORRECOVERY"
] }
```
Regards

**Comment by MarinPostma** [comment]
thanks @gwenn
