### ISSUE TITLE
DBeaver:  serverVersion must not be null

### ISSUE THREAD

**Issue by christophberger** [libsql/sqld#126]
Attempting to connect to sqld with DBeaver triggers an error message:

> Something unusual has occurred to cause the driver to fail. Please report this exception.
>   serverVersion must not be null

sqld 0.0.1 installed on macOS via Homebrew.

command:

```
sqld -d sqld.db -p 127.0.0.1:5432 --http-listen-addr=127.0.0.1:8000
``` 

DBeaver 22.3.3.202301211053

Driver: PostgreSQL
Connect by Host: localhost:5432
Local PGclient: 14.6

<img width="1195" alt="Screenshot 2023-01-29 at 22 15 42" src="https://user-images.githubusercontent.com/3835890/215356364-43d2e56f-8796-489d-8788-b84d670bc042.png">

P.S. darn cool project.

**Comment by MarinPostma** [comment]
that should not be too hard to fix, what version should sqld report though?

**Comment by MarinPostma** [comment]
I have managed to set a version that DBeaver will recognize, but it just runs into more issues. Now DBeaver tries to read from Postgres internal tables, which obviously don't exist...

**Comment by christophberger** [comment]
Thanks for testing this.

Would it be possible and feasible to prepare a SQLite file with those tables? 
I'd be happy to try that out if I can get hold of a sqld version that sends a non-null serverVersion.

OTOH, this could be a dead end if DBeaver (or any PostgreSQL driver) expects even more "Postgres" behavior that sqld does not deliver.

**Comment by MarinPostma** [comment]
@christophberger here is a draft with a working version number for DBeaver, https://github.com/libsql/sqld/pull/131

you can check out that branch and get it running with `cargo r -- -d sqld.db -p 127.0.0.1:5432 --http-listen-addr=127.0.0.1:8000` (there is also a docker file if you prefer).

That's a first step, let's see if you can get anything to work from here, and then we'll decide what the best course of action is

**Comment by MarinPostma** [comment]
we dropped support for pg wire protocol, closing
