### ISSUE TITLE
Binding params in HTTP queries

### ISSUE THREAD

**Issue by MarinPostma** [libsql/sqld#13]
It would be interesting to be able to bind parameters in HTTP queries, once #12 lands. I'm not completely sure about the API though.

Currently, there request payload looks like this:
```json
{
    "statements": [/* stmts */],
}
```
 We could for, for example add a `params` fields to the payload, with variables scoping all the statements in statement, e.g:

```json
{
    "statements": ["select * from users where name = $name"],
    "params": {
        "name": "adhoc",
    }
}
```

another option could be  statement-scoped variables, like so:
```json
{
    "statements": [{ "statement": "select * from users where name = $name", "params": {"name": "adhoc"}}],
}
```

**Comment by CodingDoug** [comment]
This issue seems closeable @MarinPostma.
