### ISSUE TITLE
Replication Protocol: Handshake

### ISSUE THREAD

**Issue by MarinPostma** [libsql/sqld#136]
Currently, the replication protocol does not perform any handshake. A reader connects to a writer and starts asking for a frame the next frame in its log.

When a reader initiates a connection with the primary, it sends a handshake request message. The writer responds to that handshake message with the id of the database, along with the current it's current WAL frame offset. If the reader was not replicating any database yet (fresh replica), it saves the id of the database and starts pulling frames from the primary. If the reader was already replicating a database, it ensures that the database id it received matches that of the database it was replicating and that it's current frame index is less that the frame index sent by the primary. If any of those invariants is broken, the replica should shut down.

**Comment by haaawk** [comment]
I think we should also check that oldest replication log entry on primary is old enough so that there's no gap between latest replication log entry received previously by the replica and the oldest replication log entry on primary
