### ISSUE TITLE
cross-fetch in the JavaScript driver doesn't seem to work everywhere

### ISSUE THREAD

**Issue by penberg** [libsql/sqld#179]
We've had multiple people point out that they had to switch to native `fetch()` because of some cross-fetch issue.

**Comment by penberg** [comment]
Looks like this `cross-fetch` just ignores native fetch: https://github.com/lquixada/cross-fetch/issues/69

**Comment by CodingDoug** [comment]
I think we can keep using cross-fetch, but don't import it as `fetch` (which masks the native fetch). Then, check to see if there is a native fetch to use before falling back to cross-fetch.
