### ISSUE TITLE
alter table not working

### ISSUE THREAD

**Issue by glommer** [libsql/sqld#228]
This is not working, but it obviously should:

```sh
$ curl -d '{"statements": ["create table foo (bar text)"] }' http://127.0.0.1:8080
[{"results":{"columns":[],"rows":[]}}]
$ curl -d '{"statements": ["alter table foo add bar text"] }' http://127.0.0.1:8080
{"error":"unsupported statement"}|
```

**Comment by haaawk** [comment]
I'm not sure sqlite supports alter table. I remember reading about some limitations around this

**Comment by haaawk** [comment]
Add column seems to be supported though https://www.sqlite.org/lang_altertable.html

**Comment by glommer** [comment]
it does. What it doesn't - and we should, some people have already begged for it, is alter table for more than one column at a time.
