### ISSUE TITLE
Load dump can fail silently

### ISSUE THREAD

**Issue by athoscouto** [libsql/sqld#234]
Load dump can fail and still return `200`.

When using `curl`, load dump will only work properly if the `--data-binary` flag is set, for instance:
```
curl $DB_URL/load-dump --data-binary @dump.sql
```

With the regular `-d` flag the response will still be `200`, but the dump will fail to load.

It doesn’t work because `-d` strips new lines from the dump file, and it seems `sqld` depends on it to parse queries.
The problem is not that `sqld` needs the new lines, but that we respond with `200` when they are not present.

`sqld` should improve our parsing and/or error detection to make sure that it only responds with `200` when the dump is correctly loaded.

**Comment by MarinPostma** [comment]
this error relates to an endpoint that does not exist anymore, closing.
