### ISSUE TITLE
Feature suggesion: ssh transport

### ISSUE THREAD

**Issue by orent** [libsql/sqld#252]
One of the best things about sqlite is that it does not require installing and managing a server. I think there is a way to maintain this simple ad-hoc model for remote connections, too.

The idea is to use a similar model to git or rsync: connect over ssh and execute a server instance inside the ssh session, passing it a path to the database. This leverages the existing authentication mechanisms and does not require configuring a persistent server process.

Any application using the libsql client library could then connect to a remote database by simply passing an ssh URL instead of the file path, without any special setup other than having sqld in the remote machine's search path. A URL parameter or environment variable could be used to pass an alternative path to the remote sqld executable, pass additional command line arguments to ssh or use another local executable instead of the default ssh.

For an mvSQLite server a persistent server process is probably required, but the connection could still be made with the same protocol without the client having to know the difference. After connecting, sqld could detect that the passed database path is actually an mvSQLite instance and act as a proxy or directly pass the file descriptors over to the server over a unix domain pipe.

**Comment by MarinPostma** [comment]
Hey @orent ! Sorry for the very late reply
I don't think this is the direction we want to go in, but thanks for the proposal 🙏
