### ISSUE TITLE
Setup test harness

### ISSUE THREAD

**Issue by MarinPostma** [libsql/sqld#29]
We now have a lot of different protocols to interact with sqld, all with specificities. On top of that is the distributed setup. This create a lot of surface to test. Let's find a way to test all of those configurations without repeating ourselves too much.

**Comment by penberg** [comment]
@MarinPostma Just a FYI: in `testing`, we have server and client tests for PostgreSQL wire protocol and in #31 I am wiring up the HTTP client tests to `make test`.
