### ISSUE TITLE
allow loadable extensions

### ISSUE THREAD

**Issue by glommer** [libsql/sqld#333]
Loadable extensions are crucial for us to tap into the ecosystem.

FWIW, I tried to get it working, but it doesn't seem trivial. 
A Couple of pointers for whoever tries this next:

I tried loading this: https://github.com/nalgeon/sqlean/blob/main/docs/uuid.md

First of all, I can get extensions to work even without any machinery. Despite adding the `load_extension` flag to rusqlite, the following code failed:

```
        unsafe {
            let _guard = rusqlite::LoadExtensionGuard::new(&x.conn).unwrap();
            let err = x.conn.load_extension("/tmp/extensions/uuid.dylib", None);
            println!("ERR: {:?}", err);
            let r = x.conn.execute("select uuid()", ());
             println!("X {:?}", r); <== fails
        }
```

This is done at connection establishment, so it doesn't even take into account other issues. But there are some:

The protocol as is today is designed to run `Program`s, which are a group of statements. I managed to add a `v1/load` endpoint that loads an extension by replacing the `Program` in `Message` with an enum like this:

```
+enum Payload {
+    Program(Program),
+    LoadExtension(String),
+}
+
 /// Internal message used to communicate between the database thread and the `LibSqlDb` handle.
 struct Message {
-    pgm: Program,
+    payload: Payload,
     resp: oneshot::Sender<(Vec<Option<QueryResult>>, State)>,
 }
```

This works well, but we'll still have issues around checking if the replicas all have the extension, etc, in order to make this really robust.

**Comment by psarna** [comment]
I had a different type of integration in mind - just preload sqld instances with some extensions (e.g. sqlean) and enable them on boot with a command-line parameter. In this model users won't ever be responsible for actually dynamically loading anything with a remote command, which makes the flow much simpler. Do you think we need the additional flexibility of letting users load extensions at any time, not just at sqld boot/reboot?

**Comment by glommer** [comment]
load-on-boot makes a couple of things simpler - but if the code above I posted doesn't work, not even that will work.

the biggest disadvantage of load-on-boot is that loading an extension is fundamentally a dynamic decision, which may make replicas unavailable for no reason. We can start with that, but dynamic loading is much more robust.

**Comment by honzasp** [comment]
What about enabling a fixed list of vetted extensions in sqld unconditionally? We cannot just load arbitrary binaries from users, so we will always allow only extensions from some finite set of reviewed extensions. Making all of them automatically available will be dramatically simpler, and I don't see many downsides.

Also, what are the use cases for this? Which extensions are most requested by the users?

**Comment by glommer** [comment]
I don't want to *load* the extensions unconditionally, because that penalizes users who don't want to use them (keep in mind that we want the local flow to keep working on the drivers, so it is not free). But definitely we should ship sqld with a docker image containing the extensions we veto, and then the users could chose to load from them.

**Comment by honzasp** [comment]
How does it penalize users who don't use them? Even if we loaded them dynamically, the latency for loading an extension should be minuscule, and we may even be able to statically compile the extensions into sqld, making the latency even lower. The code size penalty should also be quite small.

---

But you are right that using the extensions with local SQLite in our client libraries is going to be problematic. We have two options:

1. Dynamically load the native extensions. The disadvantage is that we would have to distribute the binary extensions for a large number of platforms and architectures, and it is going to be a huge pain.
2. Implement the extensions directly in the client language. The disadvantage is that we would have to reimplement the functions in every client library.

Honestly, both options seem to be very bad. So we go back to my question: what are the use cases? Being able to generate an UUID in the database is cool, but is it worth the pain? Also, if there are just a handful of functions that people are asking for, then implementing them in the client libraries might be viable.

**Comment by glommer** [comment]
if we want the local path to work- which we do - thrn you have to ship the extensions with the client as well. That increases the bundle size and adds more cold start times to functions.

Honza, the use cases depend on the extension. UUID is just a simple one I used for testing. The main ones are things like vector and semantic searches.

**Comment by haaawk** [comment]
We can allow users to enable some extensions from a predefined list of extensions. Would that work?

**Comment by honzasp** [comment]
Hmm, so what mechanism will we use to ship only a user-defined subset of extensions with the clients?

**Comment by glommer** [comment]
For typescript I think we should put them in npm, fone grained enough so that users wanting one don't have to pull them all. Rust is easier, and go is likely easier too
