### ISSUE TITLE
Support preparing statements

### ISSUE THREAD

**Issue by psarna** [libsql/sqld#351]
For validation and future optimization purposes, let's allow users to send a request to "prepare" a statement.

When a user sends a statement for preparation, we should return all useful information that gets extracted when a libSQL statement gets prepared with sqlite3_prepare, in particular:
 1. Columns used, if applicable
 2. How many parameters are expected to be bound

The same mechanism can be used to not only inspect the statement, but also to cache it client-side. Especially for stateful connections like Hrana, we could cache the statement object and give it an id. Later we can introduce an "execute" request which accepts the prepared statement id instead of the verbatim query string

**Comment by haaawk** [comment]
It would be great to also return types of the used columns. It is required for golang driver to map values to proper types. For example int or string representation of time to Time type
