### ISSUE TITLE
Are pragma statements supported in hrana? 

### ISSUE THREAD

**Issue by avinassh** [libsql/sqld#391]
I was playing with Python client and I learned that pragma statements are not working. Same with Go client or the Turso CLI: 

```go
_, err = db.ExecContext(ctx, "PRAGMA foreign_keys = OFF")
```

```python
client.execute("PRAGMA foreign_keys = OFF")
```

I got the error: 

```
SQL_PARSE_ERROR: SQL string could not be parsed: unsupported statement

# or in Turso CLI:
Error: Failed to execute SQL statement: PRAGMA journal_mode=wal;
unsupported statement
```

**Comment by haaawk** [comment]
What version of sqld are you using? foreing_keys should be supported.

**Comment by haaawk** [comment]
journal_mode is not supported at the moment and probably won't be in the near future.

**Comment by avinassh** [comment]
> What version of sqld are you using? foreing_keys should be supported.

oops, I should have mentioned I am using Turso, not sqld

**Comment by haaawk** [comment]
> > What version of sqld are you using? foreing_keys should be supported.
> 
> oops, I should have mentioned I am using Turso, not sqld

Try creating a new db of db upgrade you old one. `foreing_keys` should work. If they don't then it's a bug.

**Comment by CodingDoug** [comment]
Looks like the problem is in sqld.  The query analyzer has a typo in the names of the pragmas it allows:

https://github.com/libsql/sqld/blob/de5868f78dc135fb7ff10c5889d0b1a40afefab7/sqld/src/query_analysis.rs#L109

```
            // always ok to be served by primary
            "foreign_key" | "foreign_key_list" | "foreign_key_check" | "collation_list"
```

It should be "foreign_keys".

**Comment by haaawk** [comment]
Thanks @CodingDoug. Great catch.
And thanks @avinassh for finding that out.
