### ISSUE TITLE
@libsql/client does not handle new batch query results

### ISSUE THREAD

**Issue by CodingDoug** [libsql/sqld#40]
The return type of `execute()` return type needs to be changed to support multiple result sets that come from sqld as a result of #33.  Right now it just handles a single ResultSet. Perhaps it should be `Promise<ResultSet[]>`.

**Comment by penberg** [comment]
@CodingDoug The `execute()` API is supposed to execute just _one_ SQL statement. The `transaction()` is for batches. Did you manage to somehow run multiple statements with `execute()`?

**Comment by CodingDoug** [comment]
Actually I guess I did not actually run multiple statements.  If I use a semicolon to separate statements, it seems to silently ignores everything after the semicolon.  Could that trigger an error instead (sending more than one statement with execute) so expectations are not broken?

**Comment by CodingDoug** [comment]
Closing this in favor or #65.
