### ISSUE TITLE
Return "autocommit" status in Hrana

### ISSUE THREAD

**Issue by barbieri** [libsql/sqld#405]
The client side may need to check if the transaction is still open to properly operate. This is clear with the following sequence, based on [Python's test_dbapi.py SqliteOnConflictTests.test_on_conflict_rollback_with_explicit_transaction](https://github.com/python/cpython/blob/main/Lib/test/test_sqlite3/test_dbapi.py#L1799-L1812), reproduced below:

```sql
BEGIN;
INSERT INTO test(name) VALUES ('abort_test');
INSERT OR ROLLBACK INTO test(unique_name) VALUES ('foo');
INSERT OR ROLLBACK INTO test(unique_name) VALUES ('foo'); -- fails
```

Since it failed and the `rollback` is automatically processed, there is no way for the user to know if it must `commit` or not. While a simple and direct code like this could assume the failure implied in the rollback, it's hard to keep track of the autocommit mode.

Returning https://www.sqlite.org/c3ref/get_autocommit.html in every failed or successful statement could simplify clients that needs to do this book keeping, like my Python dbapi2 compatibility layer.

**Comment by honzasp** [comment]
This feature sounds reasonable, but the window for adding features to Hrana 2 has closed, there are already clients and servers in the wild that use Hrana 2, so we cannot change it anymore :( But we can add it to the next version of the protocol.

Incidentally, I'm not sure whether the `INSERT OR ROLLBACK` statement won't break sqld: Marin, do we correctly handle `INSERT OR ROLLBACK`, `ON CONFLICT ROLLBACK` and other implicit rollbacks in the code that tracks the transaction state of a connection? @MarinPostma

**Comment by MarinPostma** [comment]
No this is not handled yet. It makes control flow management more complex. We need to figure out how to do that ultimately. 

This could be an extension to programs as well: one could manage the control flow base on whether we are still in a transaction or not

**Comment by barbieri** [comment]
Another test that showed need for this `SAVEPOINT`, when the test does that I can't notice and then I'm emitting a `BEGIN`. The C version doesn't expose this since they always query `autocommit` directly.

As for breaking the protocol, since it's json I don't see why bother. It's rare to have people blocking "no additional properties", even when it's easy such with JSON Schema.

Do you know of any client you wrote that would break with that?

**Comment by honzasp** [comment]
Old clients won't break if we add new properties to existing structs, but there are already servers that don't implement this, so new clients will break with old servers.

Moreover, we don't have a reasonable place to piggy-back this information to; `ResponseOkMsg` and `ResponseErrorMsg` are not associated with a stream and don't exist in the new HTTP flavor of Hrana. `StmtResult` would be better, but it is only returned when the statement succeed, not when it fails.

Therefore, we will need a new request type for this, and as Marin pointed out, we may also need to extend the batch condition enum.

**Comment by MarinPostma** [comment]
can we close that @honzasp ?

**Comment by honzasp** [comment]
Yes, Hrana 3 adds functionality to query the autocommit status and to conditionally execute statements in a batch based on the autocommit status.
