### ISSUE TITLE
Referencing an invalid step in a batch condition yields unhelpful response

### ISSUE THREAD

**Issue by CodingDoug** [libsql/sqld#410]
Consider the following JSON payload to /v1/batch:

```json
{
  "batch": {
    "steps": [
      {
        "stmt": {
          "sql": "delete from ..."
        }
      },
      {
        "stmt": {
          "sql": "delete from ..."
        },
        "condition": {
          "type": "ok",
          "step": 99
        }
      }
    ]
  }
}
```

Note the invalid step number in the condition.  I would consider any number invalid if it's not an integer greater than or equal to 0, and less than the current step index - 1.

In this case, the following is logged to sqld stdout:

```
ERROR tower_http::trace::on_failure: response failed classification=Error: Could not execute batch latency=5 ms
```

And the HTTP client response is completely empty (not even a status code).

```
curl: (52) Empty reply from server
```

Instead I would expect sqld to check condition step numbers for validity, log a helpful message, and duplicate that as a proper error in the response.

@honzasp

**Comment by honzasp** [comment]
Good catch! I _thought_ that we handled this correctly, but apparently, we don't :) I'm just in the middle of improving Hrana error handling in #403, so let me fix this problem as a part of that PR.

**Comment by honzasp** [comment]
Fixed, you now get a 400 Bad Request with an error message
```
Invalid reference to step in a batch condition
```
