### ISSUE TITLE
Self-heal for replica with incompatible database

### ISSUE THREAD

**Issue by athoscouto** [libsql/sqld#449]
Replicas with a history incompatible with primaries refuse to replicate and exit with code `1`.

This is great for ensuring that the replica:
- Doesn't create an inconsistent state trying to replicate from two disjoint databases.
- Doesn't throw data away.

But it also doesn't provide a mechanism for recovering when the primary loses its replication log.

Primaries can recover their replication log after #447.
But if they do, we have to manually nuke the replica database.

It would be nice to support some kind of self-heal for replicas as well, so when the primary fixes their replication log the replicas do not require manual action.

**Comment by MarinPostma** [comment]
This should not be an issue anymore with namespaces, the database being replicated is now unambiguous, and the replica is able to self-heal.
