### ISSUE TITLE
Hrana v2: unexpected empty response for an invalid query?

### ISSUE THREAD

**Issue by psarna** [libsql/sqld#453]
I played with Hrana v2 specification a little to get a feel of it before implementing its support in https://github.com/libsql/libsql-client-rs, and I think I found unexpected behavior. When I curl the following payload to my local sqld instance, with POST method, to endpoint `localhost:8080/v2/pipeline`:
```json
{
    "baton": null,
    "requests": [
        {
            "type": "execute",
            "stmt": { "sql": "insert into nonexistent values (42)" }
        }
    ]   
}
```
, then it returns an empty response instead of an error that explains that table `nonexistent` does not exist, as it used to happen before. If the table exists, this query properly returns an ack. Is it a regression?

/cc @honzasp

**Comment by honzasp** [comment]
This seems to be a recent regression, it worked correctly in #403.

**Comment by honzasp** [comment]
Yeah, this was broken in #400. cc @MarinPostma

**Comment by MarinPostma** [comment]
Yes but this is unrelated to refactoring error handling, it's just a plain bug

**Comment by MarinPostma** [comment]
I can look into it, probably not much

**Comment by honzasp** [comment]
Ok, I will do a quick fix for now, and later we can look at error handling in more general.
