### ISSUE TITLE
triggers not working?

### ISSUE THREAD

**Issue by glommer** [libsql/sqld#464]
Given the following table:

```
CREATE TABLE users (
        id text PRIMARY KEY DEFAULT (uuid4()) NOT NULL,
        updated_at integer DEFAULT CURRENT_TIMESTAMP NOT NULL
)
```

The following trigger statement works on sqlite3, but not on sqld:

```
CREATE TRIGGER update_updated_at AFTER UPDATE ON users FOR EACH ROW BEGIN UPDATE users SET updated_at = 0 WHERE id = NEW.id; end;
```

**Comment by psarna** [comment]
This statement worked just fine on my local sqld. Did you contact it via turso shell? Perhaps the issue is there. It runs just fine both with curl, and with a dev http console at `http://localhost:8080/console` (when you run with `sqld --enable-http-console`

**Comment by MarinPostma** [comment]
Seems like the issue is solved, feel free to re-open if this happens again.
