### ISSUE TITLE
HRANA_WEBSOCKET_ERROR with client from client/web

### ISSUE THREAD

**Issue by razr22** [libsql/sqld#482]
Am trying to run drizzle transactions on the edge with turso, importing createClient from @libsql/client/web

When I send requests to any edge API ep I get this error:

- error node_modules/@libsql/client/lib-esm/hrana.js (331:15) @ mapHranaError
- error HRANA_WEBSOCKET_ERROR:
- null

**Comment by razr22** [comment]
So that was the error I was receiving when executing a transaction on the edge with the /web createClient. I was on version 0.1.6, I just updated to 0.2.2 and the issue has not reoccurred.

**Comment by CodingDoug** [comment]
Great, so we can close this issue?

**Comment by glommer** [comment]
confirmed with Zain on discord that this is fixed by updating
