### ISSUE TITLE
windows releases

### ISSUE THREAD

**Issue by gedw99** [libsql/sqld#502]
I wanted to try the s3 and WASM UDF asepcts of sqld.

in https://github.com/libsql/sqld/releases/tag/v0.16.3 there is no Windows release.

Is there a blocker on that ?

**Comment by gedw99** [comment]
I just saw that Foundationdb is a dependency and they don't have Windows releases.

the plot thickens :)

**Comment by MarinPostma** [comment]
closing in favor of #627
