### ISSUE TITLE
Wake up replicas periodically to avoid a big sync

### ISSUE THREAD

**Issue by penberg** [libsql/sqld#507]
When a replica doesn't receive client requests, it will scale to zero. Unfortunately this can result in a very long delay on the first client request if lots of writes happened on the primary while the replica was sleeping. Let's periodically wake up replicas to sync and then go back to sleep if no client requests are incoming.

**Comment by MarinPostma** [comment]
there is no way this can be done from inside sqld, since the process has to exit for it to _scale to 0_.

I'm closing this, I believe this is for the platform to handle.
