### ISSUE TITLE
Health requests reset idle shutdown counter

### ISSUE THREAD

**Issue by athoscouto** [libsql/sqld#516]
Requests sent to `/health` make the idle shutdown counter reset.
This makes it unfeasible to implement periodic health checks while relying on `--idle-shutdown-timeout-s` to implement scale to 0.

---

To reproduce:
On terminal 1:
```
watch curl localhost:8080/health -v
```

On terminal 2:
```
sqld --idle-shutdown-timeout-s 3
```
---

Expected behavior: `sqld` should shut down after 3 seconds.
What happens: `sqld` stays alive forever.

**Comment by haaawk** [comment]
I've created two alternative solutions.

1. A simple one -> https://github.com/libsql/sqld/pull/518

2. A more generic one that is based on a new `LIBSQL_EXTEND_LIFETIME` header that controls the behaviour -> https://github.com/libsql/sqld/pull/519
Example of healthcheck loop using the new header:
```
while true; do curl -H 'LIBSQL_EXTEND_LIFETIME: false' localhost:8080/health -v; sleep 2; done
```

@athoscouto @MarinPostma please let me know which approach you'd prefer.
