### ISSUE TITLE
error message when response too big is not meaningful

### ISSUE THREAD

**Issue by glommer** [libsql/sqld#529]
Testing the following node program:
```
import { createClient } from "@libsql/client";

const client = createClient({
   url: "http://127.0.0.1:8080"
});

try {
const res = await client.execute("select * from my_table");
console.log(`res2: ${JSON.stringify(res)}`);
} catch (e) {
        console.error(`error: ${e}`)
}
```

The response is > 10MB, so the expected behavior here is to fail.

However, the error message doesn't give us any indication of that. Instead:

```
error: FetchError: request to http://127.0.0.1:8080/v2/pipeline failed, reason: socket hang up
```

SQLd needs to return a meaningful error code that allows the user to understand that this is the reason why the request is failing, including saying what the limit is.

CC @CodingDoug  / @honzasp

**Comment by honzasp** [comment]
Looks like another case of wrong error handling in sqld. Will investigate.
