### ISSUE TITLE
Streaming of results

### ISSUE THREAD

**Issue by honzasp** [libsql/sqld#542]
The server and the Hrana protocol need to load the whole result set of a SQL query into memory before sending it to the client. This is a problem for large result sets, we should be able to stream the results one row at a time.

**Comment by barbieri** [comment]
You may consider batching/pages. While the policy is debatable (how to choose batch size, etc), using an array as format should be easy to do.

**Comment by MarinPostma** [comment]
@honzasp can we close this?

**Comment by honzasp** [comment]
Yes, this is implemented as cursors in Hrana 3.
