### ISSUE TITLE
Execute statements in Hrana depending on autocommit status

### ISSUE THREAD

**Issue by honzasp** [libsql/sqld#544]
To fix https://github.com/libsql/libsql-client-ts/issues/48 and implement transactions and batches correctly in the clients, we need to execute statements conditionally, based on the autocommit state of the SQL connection on the server. This would be done by extending the `BatchCond` structure in Hrana.

**Comment by MarinPostma** [comment]
@honzasp can we close this?

**Comment by honzasp** [comment]
Fixed with Hrana 3
