### ISSUE TITLE
Support `user_version` pragma

### ISSUE THREAD

**Issue by psarna** [libsql/sqld#555]
The pragma comes in 2 flavors, read-only (`pragma user_version`) and write  (`pragma user_version=X`). The write flavor simply writes an integer value into page1 at offset 60, so it's kinda a regular write, and should be rerouted to primary, while the read-only flavor can be read from replicas. Although perhaps it's better to read if from the primary as well, to make sure it works in a read-your-writes fashion.

**Comment by gamebox** [comment]
Here's my usecase to help inform your decision about where you read it from:

I'm using it to understand what version of the database has been deployed.  My migration file is executed, one statement at a time, with the PRAGMA being the final statement.  This happens in a transaction.
