### ISSUE TITLE
Add a way to ask for replication frames without blocking

### ISSUE THREAD

**Issue by psarna** [libsql/sqld#582]
Our gRPC endpoint currently reads an endless stream of `Frame`s for replication. It works great for sqld replicas, but we also need another variant for asking for as many frames as we can get without blocking. That variant will be used to implement `sync()` in our libsql client crate.

Here's a crude example on how to make our frame stream non-blocking by returning immediately once we figure out there are no more frames to replicate: <strike>https://github.com/psarna/sqld/commit/11c6ee662b56c4259ffec8bd459c624c13f53322</strike> 77a4fa0a9bbc12473ae05b96d02b97755974858e

Now, for that to be production ready, I think we just need to add one more bit of information to the `log_entries` request - whether it should be blocking or not. It should default to blocking, but `sync()` can send an opt-in parameter, say, `nonblocking = 1`, and then the stream finishes early, e.g. in the place I linked above.

**Comment by LucioFranco** [comment]
This has been completed via be9a6efc48948179427fcbee4d4a8e391a943ac6
