### ISSUE TITLE
RL8: Unknown flag: --experimental_allow_proto3_optional

### ISSUE THREAD

**Issue by tjyang** [libsql/sqld#6]
Hi

Not knowing much on protobuf. I am just playing with sqld build for RL8.

- The offending code  when compiling on RL8
```
  tonic_build::configure()
        .protoc_arg("--experimental_allow_proto3_optional")
        .compile_with_config(
            config,
            &["proto/wal_log.proto", "proto/proxy.proto"],
            &["proto"],
        )?;

```
- The error message on RL8
```
  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: Unknown flag: --experimental_allow_proto3_optional\n" }
[me@rocky8t01d server]$ protoc --version
libprotoc 3.5.0
[me@rocky8t01d server]$

```
- protoc version difference
```
[me@fedora01d sqld]$ protoc --version
libprotoc 3.14.0
[me@fedora01d sqld]$
[me@rocky8t01d sqld]$ protoc --version
libprotoc 3.5.0
[me@rocky8t01d sqld]$

```
- en

**Comment by penberg** [comment]
@tjyang Yeah, so that error message just means the `protoc` version on RH8 is too old. You can probably just install a version from protobuf release. We even had a `install-protoc.sh` script at some point: https://github.com/libsql/sqld/commit/25826696186be020ef9c6426d44541606afb9de7

**Comment by tjyang** [comment]
@penberg , thanks for the reply
