### ISSUE TITLE
Invalid/useless query params should yield an error

### ISSUE THREAD

**Issue by CodingDoug** [libsql/sqld#60]
This issue refers to the changes made in #45.

The following queries silently yield no results because the parameters don't make sense for the queries.  Instead, my opinion is that they should yield an error in order to prevent confusion.

In the below case, `$2` refers to a positional parameter that doesn't exist.  It's unclear what value actually gets bound to the statement.

```json
{
  "statements": [
    {
      "q": "select * from foo where bar = $2",
      "params": [
        "hi"
      ]
    }
  ]
}
```

In the next case, the `valx` parameter doesn't get used in the query. The query is also expecting `val`, which isn't specified.  These conditions should both yield an error (the latter moreso than the former).

```json
{
  "statements": [
    {
      "q": "select * from foo where bar = $val",
      "params": {
        "valx": "some-value"
      }
    }
  ]
}
```

I also question whether these cases (provided in the original issue) make sense to allow due to potential confusion:

```
        {"q": "select * from users where name = $1", "params": {"name": "adhoc"}}, # object is order sensitive
        {"q": "select * from users where name = ?", "params": {"name": "adhoc"}},
```

Lastly, specifying a null value for a parameter doesn't work in the case of a SQL where clause, probably because SQL is expecting "x IS NULL" instead of "x = null". If we can catch that, I'm sure developers will appreciate it.

**Comment by MarinPostma** [comment]
All of that is well-specified SQLite behavior. If a parameter is not present, it is inferred to be NULL.

> "x IS NULL" instead of "x = null"

This is because, in SQLite, `NULL != NULL`

> I also question whether these cases (provided in the original issue) make sense to allow due to potential confusion:

This is also expected SQLite behavior

@penberg WDYT? should we depart from the standard?

**Comment by psarna** [comment]
> should we depart from the standard?

I don't think so, that's not what users expect. There are probably people relying on the existing behavior, as per https://xkcd.com/1172/.

**Comment by psarna** [comment]
(unless we provide a "guardrails" configuration option, which warns about common pitfalls, as in https://cassandra.apache.org/_/blog/Apache-Cassandra-4.1-Features-Guardrails-Framework.html)

**Comment by CodingDoug** [comment]
@psarna could you share case where someone is relying on this behavior? To me, this all seems very unexpected.  I'm not sure why someone would knowingly refer to a parameter that doesn't exist.  I could see how someone might provide parameters that don't get used, for example, having a standard set of parameters that are applied to many queries.  But I also think a modern strict lint-type tool would choose to call this out, despite historical behavior.

Another alternative is to issue a warning in the response so that someone might notice this during logging/debugging.

**Comment by MarinPostma** [comment]
I thinks this is implemented now
