### ISSUE TITLE
SQL runtime errors are missing Result Codes

### ISSUE THREAD

**Issue by WilsonNet** [libsql/sqld#604]
If I run 
```sh
docker run -p 8080:8080 ghcr.io/libsql/sqld:latest
``` 

To create an instance of sqld, and then

```sh
curl --location 'http://127.0.0.1:8080' \
--header 'Content-Type: application/json' \
--data '{
    "statements": [
        {
            "q": "create table t(x int);"
        }
    ]
}'
```

I get the error, without the Result Code:

`[{"error":"table t already exists in create table t(x int); at offset 13"}] `

The above should yield the SQLite code and error message:

> SQL_INPUT_ERROR
> SQL input error: table t already exists (at offset 13)

See more at the original issue in `libsql-shell-go.git`:
https://github.com/libsql/libsql-shell-go/issues/128

**Comment by CodingDoug** [comment]
This is using the legacy HTTP interface and has been superceded by newer protocols.  It's been discussed that we might even completely drop support for it since it lacks important features (such as the error code you're looking for), and isn't used at all by modern versions of our client libraries.

**Comment by MarinPostma** [comment]
closing this
