### ISSUE TITLE
sqld doesn't persist data after termination

### ISSUE THREAD

**Issue by CodingDoug** [libsql/sqld#607]
0.18.1 commit 68719e81b74766e32546a2269bc506c5976f6274

Running sqld locally with a fresh db:

```
rm -rf primary.sqld
sqld --http-listen-addr 127.0.0.1:8080 --db-path primary.sqld
```

The database directory initially looks like this (no database file created yet):

```
primary.sqld
└── stats.json
```

Then, with the nodejs client, create a simple table:

```
create table foo (t text)
```

Now the directory is this:

```
primary.sqld
├── dbs
│   └── default
│       ├── data
│       ├── data-shm
│       ├── data-wal
│       └── wallog
└── stats.json
```

Kill sqld with ctl-c, then the directory is this:

```
primary.sqld
├── dbs
│   └── default
│       ├── data
│       └── wallog
└── stats.json
```

At this point, I observe two problems:

1. Restarting sqld and querying the new table (`select * from foo`) yields an error saying the table doesn't exist
2. Probing the db file directly with sqlite3 CLI also suggests the table doesn't exist

It seems to me that the schema should naturally persist between executions without requiring special effort.

**Comment by MarinPostma** [comment]
I just tested, and this is fixed on main. Sounds like something that #613. Feel free to re-open if you encounter the problem again in the future.
