### ISSUE TITLE
It should be an error to try to run more than one statement with client lib `execute()`

### ISSUE THREAD

**Issue by CodingDoug** [libsql/sqld#65]
If a statement string is issued with more than one command separated by semicolons, everything but the first command is silently ignored.  Instead, I think sqld should reject the query with an error saying that each string can only contain one statement.

**Comment by CodingDoug** [comment]
@MarinPostma I edited the description here.  No idea how it said something other than what I changed it to (maybe copy/pasta?).

The turso shell exhibits this problem as well if I issue multiple statements at once with a semicolon. I presume it is just passing along the given command string directly to the HTTP interface.

**Comment by MarinPostma** [comment]
@CodingDoug we can do that. It is SQLite behavior to only take the first statement into account, and ignore anything that follows, but Postgres returns an error saying it got more results than It was expecting.

**Comment by CodingDoug** [comment]
@BearLemma I believe that sqld is using a sqlite parser called lemon-rs.
https://github.com/gwenn/lemon-rs

So, I would assume that after using that to parse, it would be possible to check how many statements were found.

**Comment by MarinPostma** [comment]
@BearLemma you can change the behaviour here: https://github.com/libsql/sqld/blob/main/sqld/src/http/mod.rs#L112-L115
