### ISSUE TITLE
Enable client library to run in browser apps

### ISSUE THREAD

**Issue by CodingDoug** [libsql/sqld#68]
The only things stopping `@libsql/client` from running in the browser (in order to access sqld over HTTP) are:

1. The sqlite3 module used by the Sqlite3Driver code requires nodejs
1. sqld does not currently accept CORS requests

If the TypeScript code is simply copied into a React project, and modified to remove all references to SQLite, while also installing cross-fetch, it runs to the point of getting a CORS error.

If we make the sqlite driver its own installable module and enable cors on sqld, that should be sufficient to allow browser apps to directly make queries.

**Comment by penberg** [comment]
I wonder if we could just make the sqlite3 an optional dependency. 🤔

@MarinPostma do you know what is needed to support CORS requests in sqld?

**Comment by MarinPostma** [comment]
seems quite easy with https://docs.rs/tower-http/0.3.5/tower_http/cors/index.html
