### ISSUE TITLE
Multiple statements should be wrapped in an implicit transaction in sqld

### ISSUE THREAD

**Issue by CodingDoug** [libsql/sqld#93]
As discussed today, we should add a transaction to the batch of statements.

**Comment by MarinPostma** [comment]
Just to be clear, how's this issue different from #65?

**Comment by MarinPostma** [comment]
I'll just be blindingly wrapping the batch into a transaction. This means that if the client *also performs transactions as part of the batch* this will cause an error.

example:
```
["begin", "insert into users values ("adhoc"), "end"]
```
get transformed to:
```
["begin', "begin", "insert into users values ("adhoc"), "end", "end"]
```
hence the error.

I think that's OK, if we are clear don't he fact that batches are transactional.

**Comment by MarinPostma** [comment]
Actually, after investigating a bit further, I'm hitting another roadblock.
The issue with an implicit transaction is that it's not clear how the errors should be reported.
The current API will return a result entry for every statement in the batch. If we add an implicit transaction, there is no slot in the result array for the result of the transaction statement: Imagine `COMMIT` fails, what should the user receive?

In the end, I think it might be best to handle transactions explicitly with the client, so transactions error can be handled explicitly.

**Comment by CodingDoug** [comment]
> Just to be clear, how's this issue different from #65?

That one should cause an error when someone tries to put more than one statement into a single string separated by semicolons. Instead they should separate them out into an array of multiple statements, which would be a transaction (or just run them separately).

**Comment by CodingDoug** [comment]
> In the end, I think it might be best to handle transactions explicitly with the client, so transactions error can be handled explicitly.

I was wondering about error handling as well, but didn't think it through.

I believe the response allows for a single top-level error (a non-200 response) that is not tied to a particular result set. If anything in an implied transaction fails, could we just roll back the entire thing and generate one of these types of errors instead?
